import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@styles/globals.css'

// import '@toast-ui/editor/dist/toastui-editor.css'
import 'swiper/css'
// import 'swiper/css/lazy'
// import 'swiper/css/scrollbar'
// import 'swiper/css/navigation'
// import 'swiper/css/pagination'
import StoreProvider from '@/app/StoreProvider'
import AlertUtil from '@utils/alertUtil'
import { useSelector } from 'react-redux'
import { RootState } from '@redux/store'
import ToastUtil from '@utils/toastUtil'
import ConfirmUtil from '@utils/confirmUtil'
import React from 'react'
import NotiUtil from '@utils/notiUtil'
import { ModalReducerType } from '@redux/reducers/modal'
import { axios } from '@/api'
import LoginUtil from '@utils/loginUtil'
import { getAllCookie, getCookie } from '@utils/cookieUtil'
import SocketConnection from '@/socket/v2/SocketConnections'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className='h-full bg-white' lang='kr'>
			<body className={inter.className + ' h-full'}>
				<StoreProvider>
					<SocketConnection/>
					<LoginUtil />
					{children}
					<NotiUtil />
					<ConfirmUtil />
					<ToastUtil />
					<AlertUtil />
					<div id={'root-modal'}></div>
				</StoreProvider>
			</body>
		</html>
	)
}
